version: "3"

services:
  django:
    build: ./backend
    command: ["python", "-u", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
