version: "3"

services:
  django:
    build: ./backend
    command: ["python", "-u", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=vinhle
      - DB_PASS=password
    depends_on:
      - db
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=vinhle
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"

volumes:
  node-modules:
