# Generated by Django 2.0.1 on 2021-07-25 21:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingProcess',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ONTOS_ENT', 'Ontologies entered'), ('DB_ENT', 'Relational DB entered'), ('MAP_DONE', 'Mapping done')], default='ONTOS_ENT', max_length=10, verbose_name='State of the mapping proccess')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_field', models.FileField(upload_to='ontologies/')),
            ],
        ),
        migrations.CreateModel(
            name='RelationalDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relational_db_field', models.FileField(upload_to='relational_dbs/')),
            ],
        ),
        migrations.AddField(
            model_name='mappingprocess',
            name='ontologies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Ontology'),
        ),
        migrations.AddField(
            model_name='mappingprocess',
            name='relational_db',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapping.RelationalDB'),
        ),
    ]
