# Generated by Django 3.1 on 2021-08-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name_plural': 'Ontologies'},
        ),
        migrations.RemoveField(
            model_name='ontology',
            name='ontology_field',
        ),
        migrations.RemoveField(
            model_name='relationaldb',
            name='relational_db_field',
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontology_file',
            field=models.FileField(blank=True, null=True, upload_to='ontologies/'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontology_type',
            field=models.CharField(choices=[('URI', 'Ontology URI'), ('FILE', 'Ontology File')], default='URI', max_length=10, verbose_name='Type of the ontology uploaded'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontology_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_user',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mappingprocess',
            name='ontologies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.ontology'),
        ),
        migrations.AlterField(
            model_name='mappingprocess',
            name='relational_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.relationaldb'),
        ),
    ]
