# Generated by Django 3.1 on 2021-08-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='ontology_field',
            new_name='ontology_file',
        ),
        migrations.RemoveField(
            model_name='relationaldb',
            name='relational_db_field',
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontology_type',
            field=models.CharField(choices=[('URI', 'Ontology URI'), ('FILE', 'Ontology File')], default='URI', max_length=10, verbose_name='Type of the ontology uploaded'),
        ),
        migrations.AddField(
            model_name='ontology',
            name='ontology_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='relationaldb',
            name='relational_db_user',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
