# Generated by Django 3.1 on 2021-08-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20210804_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingprocess',
            name='ontologies',
        ),
        migrations.AddField(
            model_name='ontology',
            name='mapping_proccess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.mappingprocess'),
        ),
    ]
