# Generated by Django 3.1 on 2021-08-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20210801_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='ontology_file',
            field=models.FileField(blank=True, null=True, upload_to='ontologies/'),
        ),
    ]
