# Generated by Django 3.1 on 2021-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_mappingprocess_steps_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingprocess',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mappingprocess',
            name='valid_mapping',
            field=models.JSONField(null=True),
        ),
    ]
