# Generated by Django 3.1 on 2021-09-09 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_auto_20210904_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappingprocess',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ontology',
            name='mapping_proccess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontologies', to='mapping.mappingprocess'),
        ),
    ]
